# Generated by Django 4.2.6 on 2023-11-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person'),
        ),
    ]
